"""Initial migration

Revision ID: 3e1ed3bd2d01
Revises: 171401a2ead9
Create Date: 2025-10-06 10:05:51.098280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1ed3bd2d01'
down_revision = '171401a2ead9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
