"""Add password_hash column

Revision ID: a54ecfbe681b
Revises: 44c605f70c16
Create Date: 2025-10-03 01:11:42.350768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54ecfbe681b'
down_revision = '44c605f70c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
